/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


// STEP 4.4a - define default values for all user params
//const float defaultVolume = -96.0f;
const float defaultVolume = -3.0f;
const float defaultPan = 0.0;
const double PI = 3.1415926535897932384626433832795;

//==============================================================================
Musi45effectAudioProcessor::Musi45effectAudioProcessor()
{
    // In the constructor do any initializations that need to be done once
    
    // STEP 4.4b - set default values for all user params
//    usrParams[volumeParam].setMinMax(-96.0, 10.0);
//    usrParams[volumeParam].setWithUparam(defaultVolume);
//    
//    usrParams[panParam].setMinMax(-50.0, 50.0);
//    usrParams[panParam].setWithUparam(defaultPan);
//    
//    // set parameters internall to default and calculate aParams
//    calcAlgParams();
}

Musi45effectAudioProcessor::~Musi45effectAudioProcessor()
{
}

//==============================================================================
const String Musi45effectAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

// STEP 4.3 - return the correct number of user parameters
int Musi45effectAudioProcessor::getNumParameters()
{
    return totalNumParams;;
}

float Musi45effectAudioProcessor::getParameter (int index)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!

    // STEP 4.5 - return the slider value of a user param when called with its index
    switch (index)
    {
//        case volumeParam:
//            return usrParams[volumeParam].getVstVal();
//        case panParam:
//            return usrParams[volumeParam].getVstVal();
        default:
            return 0.0f;
    }
    
    return usrParams[index].getVstVal();
    
}

void Musi45effectAudioProcessor::setParameter (int index, float newValue)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!
    
    // STEP 4.5 - set algorithm parameters from user parameters
//    switch (index)
//    {
//        // first user param...
//        case volumeParam:
//            usrParams[volumeParam].setWithVstVal(newValue);
//            calcAlgParams();
//            break;
//        
//        // second user param...
//        case panParam:
//            usrParams[panParam].setWithVstVal(newValue);
//            calcAlgParams();
//            break;
//
//        default:
//            break;
//    }
    
//    usrParams[index].setWithVstVal(newValue);
//    calcAlgParams();
}



// I added this function to calculate new gain values whenever Volume or Pan changes
void Musi45effectAudioProcessor::calcAlgParams()
{
    double pan, tempGain, tempL, tempR;
//    
//    // calc linear gain from dB volume
//    tempGain = pow(10, usrParams[volumeParam].getUparamVal() / 20);   // the linear gain from the dB slider
//    
//    // calc L and R gains from pan setting
//    pan = usrParams[panParam].getUparamVal();
//    
//    // Constant Amplitude Pan
//    //tempR = (pan + 50.0)/100.0;       // panning gain for Right
//    //tempL = 1.0 - tempR;                    // panning gain for Left
//    
//    // OR Constant Power Pan
//    //tempL = cos((PI/2.0)*(pan + 50.0)/100.0);  // panning gain for Left
//    //tempR = sin((PI/2.0)*(pan + 50.0)/100.0);  // panning gain for Right
//    
//    // OR Ableton Style balance
//    if (pan < 0) {                    // to the left
//        tempL = 1.0;
//        tempR = 1.0 + pan/50.0;
//    }
//    else {                                  // to the right
//        tempR = 1.0;
//        tempL = 1.0 - pan/50.0;
//    }
//    
//    // we can fold in both the panning and volume into one gain for each channel
//    aParamGainL = tempGain * tempL;      // the gain for the left channel
//    aParamGainR = tempGain * tempR;      // the gain for the right channel
}

// STEP 4.7b
float Musi45effectAudioProcessor::getParameterDefaultValue (int index)
{
//    switch (index)
//    {
//        case volumeParam:
//            return defaultVolume;
//        case panParam:
//            return defaultPan;
//        default:            break;
//    }
    
    return 0.0f;
}

// STEP 4.8
const String Musi45effectAudioProcessor::getParameterName (int index)
{
//    switch (index)
//    {
//        case volumeParam:   return "volume";
//        case panParam:      return "balance";
//        default:            break;
//    }
    
    return String::empty;
}

// STEP 4.9 - not sure who calls this or when!
const String Musi45effectAudioProcessor::getParameterText (int index)
{
    return String( usrParams[index].getUparamVal() );
   // return String (getParameter (index), 2);
}

const String Musi45effectAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String Musi45effectAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool Musi45effectAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool Musi45effectAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool Musi45effectAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool Musi45effectAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool Musi45effectAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double Musi45effectAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int Musi45effectAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int Musi45effectAudioProcessor::getCurrentProgram()
{
    return 0;
}

void Musi45effectAudioProcessor::setCurrentProgram (int index)
{
}

const String Musi45effectAudioProcessor::getProgramName (int index)
{
    return String();
}

void Musi45effectAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void Musi45effectAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void Musi45effectAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void Musi45effectAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    const int numSamples = buffer.getNumSamples();
    
    // this version assumes we always have 2 channels
    float* channelDataL = buffer.getWritePointer (0);
    float* channelDataR = buffer.getWritePointer (1);
    
    for (int i = 0; i < numSamples; ++i)
    {
//        // Do some DSP magic:
//        channelDataL[i] = aParamGainL * channelDataL[i];
//        channelDataR[i] = aParamGainR * channelDataR[i];
    }
}

//==============================================================================
bool Musi45effectAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* Musi45effectAudioProcessor::createEditor()
{
    return new Musi45effectAudioProcessorEditor (*this);
}

//==============================================================================
void Musi45effectAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void Musi45effectAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new Musi45effectAudioProcessor();
}
